// blackCards.js
module.exports = [
    { id: 1, text: "Nunca olvidaré el día que descubrí ____ en el armario." },
    { id: 2, text: "La razón por la que la fiesta terminó temprano fue ____." },
    { id: 3, text: "Mi peor pesadilla comenzó con ____." },
    { id: 4, text: "No puedo mirar a mi madre igual después de ____." },
    { id: 5, text: "La última cosa que vi antes de desmayarme fue ____." },
    { id: 6, text: "Lo que encontraron en mi mochila cambió mi vida: ____." },
    { id: 7, text: "El evento más extraño de mi infancia involucró ____." },
    { id: 8, text: "La película más rara que he visto trata sobre ____." },
    { id: 9, text: "El titular del periódico decía: 'Gran escándalo por ____.'" },
    { id: 10, text: "La razón por la que fui despedido fue ____." },
    { id: 11, text: "No sé qué pasó, pero todo empezó con ____." },
    { id: 12, text: "Mi último pensamiento antes de dormir es siempre ____." },
    { id: 13, text: "La razón por la que no vuelvo al zoológico: ____." },
    { id: 14, text: "El regalo más raro que he recibido fue ____." },
    { id: 15, text: "El título de mi autobiografía sería '____'." },
    { id: 16, text: "La noticia más impactante de esta semana: ____." },
    { id: 17, text: "La verdadera causa de la extinción de los dinosaurios fue ____." },
    { id: 18, text: "Lo que me dijeron en mi horóscopo esta mañana: ____." },
    { id: 19, text: "La reunión familiar terminó en desastre por culpa de ____." },
    { id: 20, text: "Nunca pensé que ____ sería lo mejor de mi día." },
    { id: 21, text: "Mi mayor secreto fue revelado por ____." },
    { id: 22, text: "Si pudiera borrar algo de mi vida, sería ____." },
    { id: 23, text: "El peor plan que tuve con mis amigos fue ____." },
    { id: 24, text: "El verdadero motivo de mi crisis existencial es ____." },
    { id: 25, text: "El insulto más raro que he escuchado: ____." },
    { id: 26, text: "El verdadero culpable del caos en la oficina es ____." },
    { id: 27, text: "Mi vecino me odia desde que encontró ____ en su jardín." },
    { id: 28, text: "El mejor consejo que he recibido involucra ____." },
    { id: 29, text: "Lo más extraño que encontré en mi sopa fue ____." },
    { id: 30, text: "El peor consejo que he seguido: ____." },
    { id: 31, text: "Mi nueva dieta incluye mucho de ____." },
    { id: 32, text: "El motivo por el cual no puedo salir con nadie más es ____." },
    { id: 33, text: "Mi doctor me dijo que debo evitar ____ a toda costa." },
    { id: 34, text: "Nunca pensé que vería a ____ en mi vida." },
    { id: 35, text: "La razón por la cual no dormí anoche fue ____." },
    { id: 36, text: "Mi peor pesadilla se hizo realidad con ____." },
    { id: 37, text: "Nunca pensé que ____ salvaría el día." },
    { id: 38, text: "Lo que realmente destruyó mi matrimonio fue ____." },
    { id: 39, text: "El secreto familiar que nadie quería que supiera: ____." },
    { id: 40, text: "La razón por la que los extraterrestres no regresan es ____." },
    { id: 41, text: "El momento exacto en que supe que mi vida estaba arruinada: ____." },
    { id: 42, text: "Mi nuevo miedo irracional es ____." },
    { id: 43, text: "Lo que arruinó mi último día de vacaciones fue ____." },
    { id: 44, text: "El peor regalo que recibí de un ex fue ____." },
    { id: 45, text: "El mensaje más perturbador que encontré en una galleta de la fortuna decía ____." },
    { id: 46, text: "La cosa más rara que escuché en un ascensor fue ____." },
    { id: 47, text: "El incidente en el trabajo que todos intentan olvidar: ____." },
    { id: 48, text: "El consejo de mi terapeuta fue simplemente ____." },
    { id: 49, text: "El titular que nunca pensé que leería: '____ cambia el mundo'." },
    { id: 50, text: "Lo único que escuché durante el juicio fue ____." },
    { id: 51, text: "El nombre de mi grupo de WhatsApp más extraño es ____." },
    { id: 52, text: "La excusa más rara que alguien me ha dado es ____." },
    { id: 53, text: "Mi plan secreto para conquistar el mundo incluye ____." },
    { id: 54, text: "Lo peor que puedes escuchar en tu primer día de trabajo: ____." },
    { id: 55, text: "Lo que encontramos al excavar el patio trasero fue ____." },
    { id: 56, text: "La escena eliminada de mi película favorita era sobre ____." },
    { id: 57, text: "El peor error que cometió mi clon fue ____." },
    { id: 58, text: "La verdadera razón por la que el Titanic se hundió fue ____." },
    { id: 59, text: "El regalo más insensible que me dieron en mi cumpleaños fue ____." },
    { id: 60, text: "La pesadilla recurrente que tengo siempre incluye ____." },
    { id: 61, text: "El tema de la próxima reunión familiar será ____." },
    { id: 62, text: "El objeto más ridículo que alguien llevó a un velorio fue ____." },
    { id: 63, text: "Lo que realmente me hizo perder la fe en la humanidad: ____." },
    { id: 64, text: "La respuesta a la pregunta que nadie se atreve a hacer: ____." },
    { id: 65, text: "Lo último que compré online fue ____." },
    { id: 66, text: "La razón por la que no volveré a confiar en nadie: ____." },
    { id: 67, text: "El peor consejo de autoayuda que seguí fue ____." },
    { id: 68, text: "La verdad incómoda que nadie quiere admitir es ____." },
    { id: 69, text: "El texto que nunca debí enviar decía: ____." },
    { id: 70, text: "La mejor mentira que he dicho fue sobre ____." },
    { id: 71, text: "Lo que arruinó la boda fue ____." },
    { id: 72, text: "Mi momento más incómodo en una entrevista de trabajo fue ____." },
    { id: 73, text: "El peor secreto que guardé para alguien era sobre ____." },
    { id: 74, text: "Lo único que quedaba en mi lista de tareas era ____." },
    { id: 75, text: "Lo que encontré en el sótano de mi abuela fue ____." },
    { id: 76, text: "El peor final para una película sería ____." },
    { id: 77, text: "La excusa que le di al policía fue ____." },
    { id: 78, text: "Lo que encontré en el bolso de mi abuela fue ____." },
    { id: 79, text: "La peor apuesta que he hecho involucraba ____." },
    { id: 80, text: "El tema más raro que alguien propuso en una junta fue ____." },
    { id: 81, text: "Lo único que logré salvar de mi casa en llamas fue ____." },
    { id: 82, text: "El mejor plan para sobrevivir al apocalipsis incluye ____." },
    { id: 83, text: "Lo que arruinó la última cena de navidad fue ____." },
    { id: 84, text: "El peor momento para recibir una llamada telefónica es durante ____." },
    { id: 85, text: "Mi mayor arrepentimiento siempre será sobre ____." },
    { id: 86, text: "Lo más raro que encontré en mi buzón fue ____." },
    { id: 87, text: "La respuesta más absurda que recibí en un examen fue ____." },
    { id: 88, text: "El único consejo que mi abuelo me dio fue: 'Nunca confíes en ____.'" },
    { id: 89, text: "El regalo más incómodo en un intercambio fue ____." },
    { id: 90, text: "El secreto que la humanidad nunca debería descubrir es ____." },
    { id: 91, text: "Lo que me hizo renunciar a mi trabajo fue ____." },
    { id: 92, text: "El insulto más creativo que he escuchado fue ____." },
    { id: 93, text: "La última foto en mi teléfono es de ____." },
    { id: 94, text: "El desastre más grande en mi vida empezó con ____." },
    { id: 95, text: "El mejor nombre para una banda sería ____." },
    { id: 96, text: "La peor frase que leí en mi horóscopo fue: 'Prepárate para ____.'" },
    { id: 97, text: "El nombre del próximo virus global será ____." },
    { id: 98, text: "Mi jefe siempre dice: 'Nada es peor que ____.'" },
    { id: 99, text: "Lo único que me detuvo de cometer un crimen fue ____." },
    { id: 100, text: "El peor momento para tener una crisis existencial es durante ____." },
    // ... agrega tantas como quieras
  ];
