// blackCards.js
module.exports = [
    { id: 1, text: "Nunca olvidaré el día que descubrí ____ en el armario." },
    { id: 2, text: "La razón por la que la fiesta terminó temprano fue ____." },
    { id: 3, text: "Mi peor pesadilla comenzó con ____." },
    { id: 4, text: "No puedo mirar a mi madre igual después de ____." },
    { id: 5, text: "La última cosa que vi antes de desmayarme fue ____." },
    { id: 6, text: "Lo que encontraron en mi mochila cambió mi vida: ____." },
    { id: 7, text: "El evento más extraño de mi infancia involucró ____." },
    { id: 8, text: "La película más rara que he visto trata sobre ____." },
    { id: 9, text: "El titular del periódico decía: 'Gran escándalo por ____.'" },
    { id: 10, text: "La razón por la que fui despedido fue ____." },
    { id: 11, text: "No sé qué pasó, pero todo empezó con ____." },
    { id: 12, text: "Mi último pensamiento antes de dormir es siempre ____." },
    { id: 13, text: "La razón por la que no vuelvo al zoológico: ____." },
    { id: 14, text: "El regalo más raro que he recibido fue ____." },
    { id: 15, text: "El título de mi autobiografía sería '____'." },
    { id: 16, text: "La noticia más impactante de esta semana: ____." },
    { id: 17, text: "La verdadera causa de la extinción de los dinosaurios fue ____." },
    { id: 18, text: "Lo que me dijeron en mi horóscopo esta mañana: ____." },
    { id: 19, text: "La reunión familiar terminó en desastre por culpa de ____." },
    { id: 20, text: "Nunca pensé que ____ sería lo mejor de mi día." },
    { id: 21, text: "Mi mayor secreto fue revelado por ____." },
    { id: 22, text: "Si pudiera borrar algo de mi vida, sería ____." },
    { id: 23, text: "El peor plan que tuve con mis amigos fue ____." },
    { id: 24, text: "El verdadero motivo de mi crisis existencial es ____." },
    { id: 25, text: "El insulto más raro que he escuchado: ____." },
    { id: 26, text: "El verdadero culpable del caos en la oficina es ____." },
    { id: 27, text: "Mi vecino me odia desde que encontró ____ en su jardín." },
    { id: 28, text: "El mejor consejo que he recibido involucra ____." },
    { id: 29, text: "Lo más extraño que encontré en mi sopa fue ____." },
    { id: 30, text: "El peor consejo que he seguido: ____." },
    { id: 31, text: "Mi nueva dieta incluye mucho de ____." },
    { id: 32, text: "El motivo por el cual no puedo salir con nadie más es ____." },
    { id: 33, text: "Mi doctor me dijo que debo evitar ____ a toda costa." },
    { id: 34, text: "Nunca pensé que vería a ____ en mi vida." },
    { id: 35, text: "La razón por la cual no dormí anoche fue ____." },
    { id: 36, text: "Mi peor pesadilla se hizo realidad con ____." },
    { id: 37, text: "Nunca pensé que ____ salvaría el día." },
    { id: 38, text: "Lo que realmente destruyó mi matrimonio fue ____." },
    { id: 39, text: "El secreto familiar que nadie quería que supiera: ____." },
    { id: 40, text: "La razón por la que los extraterrestres no regresan es ____." },
    { id: 41, text: "El momento exacto en que supe que mi vida estaba arruinada: ____." },
    { id: 42, text: "Mi nuevo miedo irracional es ____." },
    { id: 43, text: "Lo que arruinó mi último día de vacaciones fue ____." },
    { id: 44, text: "El peor regalo que recibí de un ex fue ____." },
    { id: 45, text: "El mensaje más perturbador que encontré en una galleta de la fortuna decía ____." },
    { id: 46, text: "La cosa más rara que escuché en un ascensor fue ____." },
    { id: 47, text: "El incidente en el trabajo que todos intentan olvidar: ____." },
    { id: 48, text: "El consejo de mi terapeuta fue simplemente ____." },
    { id: 49, text: "El titular que nunca pensé que leería: '____ cambia el mundo'." },
    { id: 50, text: "Lo único que escuché durante el juicio fue ____." },
    { id: 51, text: "El nombre de mi grupo de WhatsApp más extraño es ____." },
    { id: 52, text: "La excusa más rara que alguien me ha dado es ____." },
    { id: 53, text: "Mi plan secreto para conquistar el mundo incluye ____." },
    { id: 54, text: "Lo peor que puedes escuchar en tu primer día de trabajo: ____." },
    { id: 55, text: "Lo que encontramos al excavar el patio trasero fue ____." },
    { id: 56, text: "La escena eliminada de mi película favorita era sobre ____." },
    { id: 57, text: "El peor error que cometió mi clon fue ____." },
    { id: 58, text: "La verdadera razón por la que el Titanic se hundió fue ____." },
    { id: 59, text: "El regalo más insensible que me dieron en mi cumpleaños fue ____." },
    { id: 60, text: "La pesadilla recurrente que tengo siempre incluye ____." },
    { id: 61, text: "El tema de la próxima reunión familiar será ____." },
    { id: 62, text: "El objeto más ridículo que alguien llevó a un velorio fue ____." },
    { id: 63, text: "Lo que realmente me hizo perder la fe en la humanidad: ____." },
    { id: 64, text: "La respuesta a la pregunta que nadie se atreve a hacer: ____." },
    { id: 65, text: "Lo último que compré online fue ____." },
    { id: 66, text: "La razón por la que no volveré a confiar en nadie: ____." },
    { id: 67, text: "El peor consejo de autoayuda que seguí fue ____." },
    { id: 68, text: "La verdad incómoda que nadie quiere admitir es ____." },
    { id: 69, text: "El texto que nunca debí enviar decía: ____." },
    { id: 70, text: "La mejor mentira que he dicho fue sobre ____." },
    { id: 71, text: "Lo que arruinó la boda fue ____." },
    { id: 72, text: "Mi momento más incómodo en una entrevista de trabajo fue ____." },
    { id: 73, text: "El peor secreto que guardé para alguien era sobre ____." },
    { id: 74, text: "Lo único que quedaba en mi lista de tareas era ____." },
    { id: 75, text: "Lo que encontré en el sótano de mi abuela fue ____." },
    { id: 76, text: "El peor final para una película sería ____." },
    { id: 77, text: "La excusa que le di al policía fue ____." },
    { id: 78, text: "Lo que encontré en el bolso de mi abuela fue ____." },
    { id: 79, text: "La peor apuesta que he hecho involucraba ____." },
    { id: 80, text: "El tema más raro que alguien propuso en una junta fue ____." },
    { id: 81, text: "Lo único que logré salvar de mi casa en llamas fue ____." },
    { id: 82, text: "El mejor plan para sobrevivir al apocalipsis incluye ____." },
    { id: 83, text: "Lo que arruinó la última cena de navidad fue ____." },
    { id: 84, text: "El peor momento para recibir una llamada telefónica es durante ____." },
    { id: 85, text: "Mi mayor arrepentimiento siempre será sobre ____." },
    { id: 86, text: "Lo más raro que encontré en mi buzón fue ____." },
    { id: 87, text: "La respuesta más absurda que recibí en un examen fue ____." },
    { id: 88, text: "El único consejo que mi abuelo me dio fue: 'Nunca confíes en ____.'" },
    { id: 89, text: "El regalo más incómodo en un intercambio fue ____." },
    { id: 90, text: "El secreto que la humanidad nunca debería descubrir es ____." },
    { id: 91, text: "Lo que me hizo renunciar a mi trabajo fue ____." },
    { id: 92, text: "El insulto más creativo que he escuchado fue ____." },
    { id: 93, text: "La última foto en mi teléfono es de ____." },
    { id: 94, text: "El desastre más grande en mi vida empezó con ____." },
    { id: 95, text: "El mejor nombre para una banda sería ____." },
    { id: 96, text: "La peor frase que leí en mi horóscopo fue: 'Prepárate para ____.'" },
    { id: 97, text: "El nombre del próximo virus global será ____." },
    { id: 98, text: "Mi jefe siempre dice: 'Nada es peor que ____.'" },
    { id: 99, text: "Lo único que me detuvo de cometer un crimen fue ____." },
    { id: 100, text: "El peor momento para tener una crisis existencial es durante ____." },
    { id: 101, text: "una colección de sellos maldita" },
    { id: 102, text: "el último mensaje de un loro espía" },
    { id: 103, text: "mi reflejo que me juzga" },
    { id: 104, text: "una piñata llena de arroz crudo" },
    { id: 105, text: "un ventilador que nunca deja de girar" },
    { id: 106, text: "el ruido de las uñas en una pizarra" },
    { id: 107, text: "una llamada telefónica desde el más allá" },
    { id: 108, text: "un vampiro alérgico a la sangre" },
    { id: 109, text: "el último post-it de mi jefe" },
    { id: 110, text: "un incendio provocado por un microondas" },
    { id: 111, text: "la invasión de hormigas vengativas" },
    { id: 112, text: "una máquina expendedora que da consejos de vida" },
    { id: 113, text: "un muñeco de nieve que da miedo" },
    { id: 114, text: "una carta de amor escrita por un gato" },
    { id: 115, text: "un teclado lleno de lágrimas" },
    { id: 116, text: "un perro que sabe demasiado" },
    { id: 117, text: "el último deseo de un pez dorado" },
    { id: 118, text: "una conferencia sobre cómo perder dinero" },
    { id: 119, text: "una momia que quiere ser influencer" },
    { id: 120, text: "el recuerdo de mi peor caída" },
    { id: 121, text: "el último helado del mundo" },
    { id: 122, text: "la alarma que nunca se apaga" },
    { id: 123, text: "un calcetín con vida propia" },
    { id: 124, text: "una araña gigante en la ducha" },
    { id: 125, text: "una pelota de playa en el espacio" },
    { id: 126, text: "el peor invento de la humanidad" },
    { id: 127, text: "el árbol que siempre da frutos podridos" },
    { id: 128, text: "una sartén que cuenta chistes malos" },
    { id: 129, text: "el fantasma de una nevera antigua" },
    { id: 130, text: "una sopa que parece infinita" },
    { id: 131, text: "un regalo que nadie quiere abrir" },
    { id: 132, text: "el peor sombrero que he visto" },
    { id: 133, text: "una sandía que parece un corazón humano" },
    { id: 134, text: "el pájaro que nunca aprendió a volar" },
    { id: 135, text: "una fábrica de paraguas en un desierto" },
    { id: 136, text: "una galleta que siempre cae al suelo" },
    { id: 137, text: "el último botón de un ascensor" },
    { id: 138, text: "un reloj que marca las horas negativas" },
    { id: 139, text: "el ladrón más torpe de la historia" },
    { id: 140, text: "un marciano que se perdió en la Tierra" },
    { id: 141, text: "el último chicle del planeta" },
    { id: 142, text: "una silla que siempre se rompe" },
    { id: 143, text: "el peor dibujo que hice en mi vida" },
    { id: 144, text: "el grito de una cabra enfadada" },
    { id: 145, text: "un acordeón desafinado" },
    { id: 146, text: "un árbol de navidad lleno de arañas" },
    { id: 147, text: "la pizza más triste que he visto" },
    { id: 148, text: "un sombrero que da mala suerte" },
    { id: 149, text: "una biblioteca llena de libros en blanco" },
    { id: 150, text: "el diente de oro de un pirata" },
    { id: 151, text: "una lámpara que canta canciones de cuna" },
    { id: 152, text: "el último mensaje de una paloma mensajera" },
    { id: 153, text: "un video viral que arruinó mi vida" },
    { id: 154, text: "una nevera que come comida" },
    { id: 155, text: "un reloj que grita la hora" },
    { id: 156, text: "un sombrero que siempre pierde apuestas" },
    { id: 157, text: "una ducha que te juzga mientras cantas" },
    { id: 158, text: "el último deseo de un genio cansado" },
    { id: 159, text: "un cactus que cuenta secretos" },
    { id: 160, text: "una carta de despido escrita con emojis" },
    { id: 161, text: "un vaso lleno de culpa" },
    { id: 162, text: "el peor pastel de cumpleaños" },
    { id: 163, text: "un bolígrafo que escribe poemas tristes" },
    { id: 164, text: "una jirafa en un monopatín" },
    { id: 165, text: "el mejor insulto que he escuchado" },
    { id: 166, text: "una llamada perdida de un desconocido" },
    { id: 167, text: "la huella digital de un gato" },
    { id: 168, text: "un paraguas que nunca se abre" },
    { id: 169, text: "un cocodrilo en una bañera" },
    { id: 170, text: "el sombrero de un espantapájaros" },
    { id: 171, text: "una carta sin remitente" },
    { id: 172, text: "un disco rayado que no para de sonar" },
    { id: 173, text: "el último diente de leche" },
    { id: 174, text: "un espejo que solo muestra tu peor cara" },
    { id: 175, text: "una puerta que nunca se abre" },
    { id: 176, text: "un boleto de lotería quemado" },
    { id: 177, text: "un sombrero lleno de secretos" },
    { id: 178, text: "un dragón que teme al fuego" },
    { id: 179, text: "un ladrillo pintado de oro" },
    { id: 180, text: "el fantasma de una lámpara rota" },
    { id: 181, text: "una mariposa hecha de papel" },
    { id: 182, text: "el sonido de un violín desafinado" },
    { id: 183, text: "un piano lleno de arena" },
    { id: 184, text: "la última risa de un payaso triste" },
    { id: 185, text: "el fantasma de un ratón" },
    { id: 186, text: "una oveja con gafas de sol" },
    { id: 187, text: "un cohete que nunca despega" },
    { id: 188, text: "un oso polar en un sauna" },
    { id: 189, text: "un cuadro que siempre cambia de forma" },
    { id: 190, text: "el silencio de una biblioteca vacía" },
    { id: 191, text: "un jardín lleno de cactus parlantes" },
    { id: 192, text: "una botella con un mensaje críptico" },
    { id: 193, text: "un barco que flota en el aire" },
    { id: 194, text: "la última llave de un candado perdido" },
    { id: 195, text: "un pez en un charco de lágrimas" },
    { id: 196, text: "un ratón con un sombrero de copa" },
    { id: 197, text: "una jaula sin puertas" },
    { id: 198, text: "el zapato perdido de un gigante" },
    { id: 199, text: "un trébol con seis hojas" },
    { id: 200, text: "el eco de un grito lejano" },
    { id: 201, text: "una lista de compras escrita con sangre" },
    { id: 202, text: "un muñeco de nieve en un horno" },
    { id: 203, text: "el conejo de Pascua desempleado" },
    { id: 204, text: "una planta carnívora con remordimientos" },
    { id: 205, text: "un médico que nunca aprobó el examen final" },
    { id: 206, text: "un paraguas que susurra secretos" },
    { id: 207, text: "la biblioteca de los libros que nadie quiere leer" },
    { id: 208, text: "una canción de cuna aterradora" },
    { id: 209, text: "una caja de galletas llena de arrepentimiento" },
    { id: 210, text: "el pez que siempre miente" },
    { id: 211, text: "un violinista tocando en el Titanic 2" },
    { id: 212, text: "el cactus que se arrepintió de abrazar" },
    { id: 213, text: "el último diente de un dinosaurio" },
    { id: 214, text: "un payaso en un juicio" },
    { id: 215, text: "un oso polar en un columpio" },
    { id: 216, text: "una sombra que no se parece a ti" },
    { id: 217, text: "un grito atrapado en una botella" },
    { id: 218, text: "el fantasma de una canción olvidada" },
    { id: 219, text: "una camiseta que huele a fracaso" },
    { id: 220, text: "el lado oscuro del arcoíris" },
    { id: 221, text: "un robot que llora lágrimas de aceite" },
    { id: 222, text: "una marioneta con complejo de superioridad" },
    { id: 223, text: "el peor tuit de mi vida" },
    { id: 224, text: "un lápiz que nunca escribe lo que piensas" },
    { id: 225, text: "un tren que solo viaja al pasado" },
    { id: 226, text: "el sombrero de un mago fracasado" },
    { id: 227, text: "un ataúd con Wi-Fi" },
    { id: 228, text: "la última broma que contaron en un funeral" },
    { id: 229, text: "un monstruo que se asusta de sí mismo" },
    { id: 230, text: "la risa más incómoda del mundo" },
    { id: 231, text: "un astronauta atrapado en su propio casco" },
    { id: 232, text: "el fantasma que vive en mi armario" },
    { id: 233, text: "un pastel de cumpleaños lleno de dinamita" },
    { id: 234, text: "el peor final de un libro jamás escrito" },
    { id: 235, text: "un superhéroe que odia a los niños" },
    { id: 236, text: "un chef que nunca prueba su comida" },
    { id: 237, text: "un billete de lotería que siempre pierde" },
    { id: 238, text: "el jefe que siempre aparece en mis pesadillas" },
    { id: 239, text: "una taza de café que nunca se vacía" },
    { id: 240, text: "el eco de una discusión familiar" },
    { id: 241, text: "un sombrero que me grita insultos" },
    { id: 242, text: "un piano desafinado en una boda" },
    { id: 243, text: "la peor reunión familiar de la historia" },
    { id: 244, text: "un delfín con planes de dominación mundial" },
    { id: 245, text: "el olor de un fracaso" },
    { id: 246, text: "una obra de teatro escrita por un perro" },
    { id: 247, text: "el tesoro que nadie quiso encontrar" },
    { id: 248, text: "un reloj que se detuvo en el peor momento" },
    { id: 249, text: "una biblioteca llena de excusas" },
    { id: 250, text: "un huracán de disculpas" },
    { id: 251, text: "el ruido de un corazón roto" },
    { id: 252, text: "una lámpara que siempre dice la verdad" },
    { id: 253, text: "el silencio incómodo de un ascensor" },
    { id: 254, text: "un ejército de gansos enojados" },
    { id: 255, text: "un museo de errores" },
    { id: 256, text: "una taza de té llena de secretos" },
    { id: 257, text: "el fantasma de un bolígrafo perdido" },
    { id: 258, text: "una disculpa escrita en una servilleta" },
    { id: 259, text: "un dragón que colecciona sueños rotos" },
    { id: 260, text: "el peor meme de internet" },
    { id: 261, text: "el hombre que vendió la luna" },
    { id: 262, text: "una silla que nunca deja de chirriar" },
    { id: 263, text: "la biblioteca de los libros más odiados" },
    { id: 264, text: "el olor de un secreto revelado" },
    { id: 265, text: "un tigre con miedo a las ovejas" },
    { id: 266, text: "el sonido de la lluvia en una tumba" },
    { id: 267, text: "una brújula que solo apunta al sur" },
    { id: 268, text: "un sombrero lleno de abejas" },
    { id: 269, text: "el zapato de un gigante olvidado" },
    { id: 270, text: "una torre de cartas que nunca cae" },
    { id: 271, text: "el tesoro más decepcionante del mundo" },
    { id: 272, text: "una nevera que canta ópera" },
    { id: 273, text: "el día que olvidé mi propia sombra" },
    { id: 274, text: "una paloma con complejo de artista" },
    { id: 275, text: "el sonido de una promesa rota" },
    { id: 276, text: "un león que se convirtió en vegetariano" },
    { id: 277, text: "una máquina del tiempo que solo va al martes" },
    { id: 278, text: "un espejo que nunca dice la verdad" },
    { id: 279, text: "el elefante que se olvidó de todo" },
    { id: 280, text: "una vela que nunca se apaga" },
    { id: 281, text: "un fantasma que canta boleros" },
    { id: 282, text: "un viaje que nunca terminó" },
    { id: 283, text: "una mesa llena de culpas" },
    { id: 284, text: "el perfume de la nostalgia" },
    { id: 285, text: "un recuerdo que no me pertenece" },
    { id: 286, text: "una nube con forma de arrepentimiento" },
    { id: 287, text: "un rompecabezas con piezas que sobran" },
    { id: 288, text: "una carta que nunca llegó a destino" },
    { id: 289, text: "el llanto de un payaso solitario" },
    { id: 290, text: "un camello que extraña el desierto" },
    { id: 291, text: "la última lágrima de un héroe olvidado" },
    { id: 292, text: "una canción que nunca termina" },
    { id: 293, text: "el peor chiste contado en una boda" },
    { id: 294, text: "el sonido de la verdad" },
    { id: 295, text: "una piedra que siempre rueda" },
    { id: 296, text: "un circo sin público" },
    { id: 297, text: "la peor selfie del mundo" },
    { id: 298, text: "una botella de vino llena de lágrimas" },
    { id: 299, text: "un juego que nunca se puede ganar" },
    { id: 300, text: "el mejor error de mi vida" }
    // ... agrega tantas como quieras
  ];
