// whiteCards.js
module.exports = [
    { id: 1, text: "un mapache con un cuchillo" },
    { id: 2, text: "una tostadora en llamas" },
    { id: 3, text: "mi vecino construyendo un cohete casero" },
    { id: 4, text: "un desfile de elefantes en mi jardín" },
    { id: 5, text: "mi perro hablando francés" },
    { id: 6, text: "una invasión de patos agresivos" },
    { id: 7, text: "una piñata llena de abejas" },
    { id: 8, text: "la cara de mi jefe en un billete" },
    { id: 9, text: "una bicicleta que no avanza" },
    { id: 10, text: "un pingüino fumando un cigarro" },
    { id: 11, text: "un robot con crisis existencial" },
    { id: 12, text: "una tormenta de fideos" },
    { id: 13, text: "una vaca con zapatos de tacón" },
    { id: 14, text: "el silencio incómodo en una boda" },
    { id: 15, text: "un cactus llorando lágrimas reales" },
    { id: 16, text: "mi peor calificación convertida en tatuaje" },
    { id: 17, text: "el olor de la desesperación" },
    { id: 18, text: "mi profesor disfrazado de payaso" },
    { id: 19, text: "una serpiente con sombrero" },
    { id: 20, text: "la abuela del presidente" },
    { id: 21, text: "una nevera llena de helado derretido" },
    { id: 22, text: "un unicornio robando bancos" },
    { id: 23, text: "una silla de ruedas con turbo" },
    { id: 24, text: "un tanque lleno de peces parlantes" },
    { id: 25, text: "una momia haciendo yoga" },
    { id: 26, text: "el espíritu vengativo de mi microondas" },
    { id: 27, text: "mi mejor amigo siendo arrestado por robar queso" },
    { id: 28, text: "un oso intentando hacer panqueques" },
    { id: 29, text: "un genio que solo concede deseos inútiles" },
    { id: 30, text: "la planta que se comió a mi hermana" },
    { id: 31, text: "el apocalipsis zombi, pero lento" },
    { id: 32, text: "un dragón con miedo a volar" },
    { id: 33, text: "una almohada llena de secretos" },
    { id: 34, text: "el álbum de fotos de un extraterrestre" },
    { id: 35, text: "una carta de amor mal escrita" },
    { id: 36, text: "un barco pirata con solo un pirata" },
    { id: 37, text: "una camisa que te odia" },
    { id: 38, text: "un huracán de chanclas" },
    { id: 39, text: "la peor sopa de la historia" },
    { id: 40, text: "un enjambre de mosquitos en un teatro" },
    { id: 41, text: "un payaso enojado" },
    { id: 42, text: "el espíritu de mi ex" },
    { id: 43, text: "una sandía explosiva" },
    { id: 44, text: "mi abuela bailando reguetón" },
    { id: 45, text: "un político buscando sinceridad" },
    { id: 46, text: "una conferencia sobre cómo fracasar" },
    { id: 47, text: "un panadero que odia el pan" },
    { id: 48, text: "el jefe que nadie invitó al cumpleaños" },
    { id: 49, text: "la peor canción del mundo en un loop infinito" },
    { id: 50, text: "una familia discutiendo en la fila del supermercado" },
    { id: 51, text: "un cuadro abstracto que da miedo" },
    { id: 52, text: "la leyenda del baño cerrado en un tren" },
    { id: 53, text: "un gato con más seguidores que yo en redes sociales" },
    { id: 54, text: "una pila de tareas que nunca desaparecerá" },
    { id: 55, text: "el cumpleaños de alguien que olvidaste" },
    { id: 56, text: "un pez peleando con su reflejo" },
    { id: 57, text: "mi esperanza perdida en una caja de pizza vacía" },
    { id: 58, text: "una fiesta que nadie recuerda" },
    { id: 59, text: "una estatua de cera que parece viva" },
    { id: 60, text: "la palabra 'perdón' mal utilizada" },
    { id: 61, text: "la selfie de un criminal en fuga" },
    { id: 62, text: "una rifa con premios inútiles" },
    { id: 63, text: "una pelea absurda por un cargador de móvil" },
    { id: 64, text: "el reloj que siempre marca la hora incorrecta" },
    { id: 65, text: "una lista de deseos que incluye 'desear menos'" },
    { id: 66, text: "un payaso en una rueda de prensa" },
    { id: 67, text: "la lámpara que juraste que era mágica" },
    { id: 68, text: "un tren que no llega a ningún lado" },
    { id: 69, text: "un traje que huele a arrepentimiento" },
    { id: 70, text: "el libro que me arruinó la infancia" },
    { id: 71, text: "un perfume llamado 'desesperación'" },
    { id: 72, text: "la casa que todos dicen que está embrujada" },
    { id: 73, text: "un globo que arruinó un funeral" },
    { id: 74, text: "la nota de suicidio de un robot" },
    { id: 75, text: "una cabra en una sala de espera" },
    { id: 76, text: "el beso de Judas" },
    { id: 77, text: "un cirujano con miedo a la sangre" },
    { id: 78, text: "un paquete que nunca debí abrir" },
    { id: 79, text: "la última palabra de un pirata" },
    { id: 80, text: "un dictador en un concurso de canto" },
    { id: 81, text: "un pastel que explota al cortarlo" },
    { id: 82, text: "un regalo de navidad lleno de lágrimas" },
    { id: 83, text: "la razón por la que me dejaron en el altar" },
    { id: 84, text: "el payaso de las pesadillas de mi infancia" },
    { id: 85, text: "un perro al que nunca le lanzaron la pelota" },
    { id: 86, text: "un incendio en una fábrica de peluches" },
    { id: 87, text: "una pluma que escribe insultos sola" },
    { id: 88, text: "un tiburón en una piscina pública" },
    { id: 89, text: "el arte moderno más ofensivo que he visto" },
    { id: 90, text: "el premio Nobel de la mediocridad" },
    { id: 91, text: "una silla eléctrica con Wi-Fi" },
    { id: 92, text: "el ruido de un sueño roto" },
    { id: 93, text: "el bebé más feo del mundo" },
    { id: 94, text: "una iglesia vacía en navidad" },
    { id: 95, text: "el apocalipsis más decepcionante de la historia" },
    { id: 96, text: "un espíritu vengativo en mi microondas" },
    { id: 97, text: "la única persona que me dijo la verdad" },
    { id: 98, text: "un cupcake con mensajes pasivo-agresivos" },
    { id: 99, text: "el fantasma de mi mala decisión" },
    { id: 100, text: "un paraguas roto en medio de una tormenta" },
    { id: 101, text: "una colección de sellos maldita" },
    { id: 102, text: "el último mensaje de un loro espía" },
    { id: 103, text: "mi reflejo que me juzga" },
    { id: 104, text: "una piñata llena de arroz crudo" },
    { id: 105, text: "un ventilador que nunca deja de girar" },
    { id: 106, text: "el ruido de las uñas en una pizarra" },
    { id: 107, text: "una llamada telefónica desde el más allá" },
    { id: 108, text: "un vampiro alérgico a la sangre" },
    { id: 109, text: "el último post-it de mi jefe" },
    { id: 110, text: "un incendio provocado por un microondas" },
    { id: 111, text: "la invasión de hormigas vengativas" },
    { id: 112, text: "una máquina expendedora que da consejos de vida" },
    { id: 113, text: "un muñeco de nieve que da miedo" },
    { id: 114, text: "una carta de amor escrita por un gato" },
    { id: 115, text: "un teclado lleno de lágrimas" },
    { id: 116, text: "un perro que sabe demasiado" },
    { id: 117, text: "el último deseo de un pez dorado" },
    { id: 118, text: "una conferencia sobre cómo perder dinero" },
    { id: 119, text: "una momia que quiere ser influencer" },
    { id: 120, text: "el recuerdo de mi peor caída" },
    { id: 121, text: "el último helado del mundo" },
    { id: 122, text: "la alarma que nunca se apaga" },
    { id: 123, text: "un calcetín con vida propia" },
    { id: 124, text: "una araña gigante en la ducha" },
    { id: 125, text: "una pelota de playa en el espacio" },
    { id: 126, text: "el peor invento de la humanidad" },
    { id: 127, text: "el árbol que siempre da frutos podridos" },
    { id: 128, text: "una sartén que cuenta chistes malos" },
    { id: 129, text: "el fantasma de una nevera antigua" },
    { id: 130, text: "una sopa que parece infinita" },
    { id: 131, text: "un regalo que nadie quiere abrir" },
    { id: 132, text: "el peor sombrero que he visto" },
    { id: 133, text: "una sandía que parece un corazón humano" },
    { id: 134, text: "el pájaro que nunca aprendió a volar" },
    { id: 135, text: "una fábrica de paraguas en un desierto" },
    { id: 136, text: "una galleta que siempre cae al suelo" },
    { id: 137, text: "el último botón de un ascensor" },
    { id: 138, text: "un reloj que marca las horas negativas" },
    { id: 139, text: "el ladrón más torpe de la historia" },
    { id: 140, text: "un marciano que se perdió en la Tierra" },
    { id: 141, text: "el último chicle del planeta" },
    { id: 142, text: "una silla que siempre se rompe" },
    { id: 143, text: "el peor dibujo que hice en mi vida" },
    { id: 144, text: "el grito de una cabra enfadada" },
    { id: 145, text: "un acordeón desafinado" },
    { id: 146, text: "un árbol de navidad lleno de arañas" },
    { id: 147, text: "la pizza más triste que he visto" },
    { id: 148, text: "un sombrero que da mala suerte" },
    { id: 149, text: "una biblioteca llena de libros en blanco" },
    { id: 150, text: "el diente de oro de un pirata" },
    { id: 151, text: "una lámpara que canta canciones de cuna" },
    { id: 152, text: "el último mensaje de una paloma mensajera" },
    { id: 153, text: "un video viral que arruinó mi vida" },
    { id: 154, text: "una nevera que come comida" },
    { id: 155, text: "un reloj que grita la hora" },
    { id: 156, text: "un sombrero que siempre pierde apuestas" },
    { id: 157, text: "una ducha que te juzga mientras cantas" },
    { id: 158, text: "el último deseo de un genio cansado" },
    { id: 159, text: "un cactus que cuenta secretos" },
    { id: 160, text: "una carta de despido escrita con emojis" },
    { id: 161, text: "un vaso lleno de culpa" },
    { id: 162, text: "el peor pastel de cumpleaños" },
    { id: 163, text: "un bolígrafo que escribe poemas tristes" },
    { id: 164, text: "una jirafa en un monopatín" },
    { id: 165, text: "el mejor insulto que he escuchado" },
    { id: 166, text: "una llamada perdida de un desconocido" },
    { id: 167, text: "la huella digital de un gato" },
    { id: 168, text: "un paraguas que nunca se abre" },
    { id: 169, text: "un cocodrilo en una bañera" },
    { id: 170, text: "el sombrero de un espantapájaros" },
    { id: 171, text: "una carta sin remitente" },
    { id: 172, text: "un disco rayado que no para de sonar" },
    { id: 173, text: "el último diente de leche" },
    { id: 174, text: "un espejo que solo muestra tu peor cara" },
    { id: 175, text: "una puerta que nunca se abre" },
    { id: 176, text: "un boleto de lotería quemado" },
    { id: 177, text: "un sombrero lleno de secretos" },
    { id: 178, text: "un dragón que teme al fuego" },
    { id: 179, text: "un ladrillo pintado de oro" },
    { id: 180, text: "el fantasma de una lámpara rota" },
    { id: 181, text: "una mariposa hecha de papel" },
    { id: 182, text: "el sonido de un violín desafinado" },
    { id: 183, text: "un piano lleno de arena" },
    { id: 184, text: "la última risa de un payaso triste" },
    { id: 185, text: "el fantasma de un ratón" },
    { id: 186, text: "una oveja con gafas de sol" },
    { id: 187, text: "un cohete que nunca despega" },
    { id: 188, text: "un oso polar en un sauna" },
    { id: 189, text: "un cuadro que siempre cambia de forma" },
    { id: 190, text: "el silencio de una biblioteca vacía" },
    { id: 191, text: "un jardín lleno de cactus parlantes" },
    { id: 192, text: "una botella con un mensaje críptico" },
    { id: 193, text: "un barco que flota en el aire" },
    { id: 194, text: "la última llave de un candado perdido" },
    { id: 195, text: "un pez en un charco de lágrimas" },
    { id: 196, text: "un ratón con un sombrero de copa" },
    { id: 197, text: "una jaula sin puertas" },
    { id: 198, text: "el zapato perdido de un gigante" },
    { id: 199, text: "un trébol con seis hojas" },
    { id: 200, text: "el eco de un grito lejano" },
    { id: 201, text: "una lista de compras escrita con sangre" },
    { id: 202, text: "un muñeco de nieve en un horno" },
    { id: 203, text: "el conejo de Pascua desempleado" },
    { id: 204, text: "una planta carnívora con remordimientos" },
    { id: 205, text: "un médico que nunca aprobó el examen final" },
    { id: 206, text: "un paraguas que susurra secretos" },
    { id: 207, text: "la biblioteca de los libros que nadie quiere leer" },
    { id: 208, text: "una canción de cuna aterradora" },
    { id: 209, text: "una caja de galletas llena de arrepentimiento" },
    { id: 210, text: "el pez que siempre miente" },
    { id: 211, text: "un violinista tocando en el Titanic 2" },
    { id: 212, text: "el cactus que se arrepintió de abrazar" },
    { id: 213, text: "el último diente de un dinosaurio" },
    { id: 214, text: "un payaso en un juicio" },
    { id: 215, text: "un oso polar en un columpio" },
    { id: 216, text: "una sombra que no se parece a ti" },
    { id: 217, text: "un grito atrapado en una botella" },
    { id: 218, text: "el fantasma de una canción olvidada" },
    { id: 219, text: "una camiseta que huele a fracaso" },
    { id: 220, text: "el lado oscuro del arcoíris" },
    { id: 221, text: "un robot que llora lágrimas de aceite" },
    { id: 222, text: "una marioneta con complejo de superioridad" },
    { id: 223, text: "el peor tuit de mi vida" },
    { id: 224, text: "un lápiz que nunca escribe lo que piensas" },
    { id: 225, text: "un tren que solo viaja al pasado" },
    { id: 226, text: "el sombrero de un mago fracasado" },
    { id: 227, text: "un ataúd con Wi-Fi" },
    { id: 228, text: "la última broma que contaron en un funeral" },
    { id: 229, text: "un monstruo que se asusta de sí mismo" },
    { id: 230, text: "la risa más incómoda del mundo" },
    { id: 231, text: "un astronauta atrapado en su propio casco" },
    { id: 232, text: "el fantasma que vive en mi armario" },
    { id: 233, text: "un pastel de cumpleaños lleno de dinamita" },
    { id: 234, text: "el peor final de un libro jamás escrito" },
    { id: 235, text: "un superhéroe que odia a los niños" },
    { id: 236, text: "un chef que nunca prueba su comida" },
    { id: 237, text: "un billete de lotería que siempre pierde" },
    { id: 238, text: "el jefe que siempre aparece en mis pesadillas" },
    { id: 239, text: "una taza de café que nunca se vacía" },
    { id: 240, text: "el eco de una discusión familiar" },
    { id: 241, text: "un sombrero que me grita insultos" },
    { id: 242, text: "un piano desafinado en una boda" },
    { id: 243, text: "la peor reunión familiar de la historia" },
    { id: 244, text: "un delfín con planes de dominación mundial" },
    { id: 245, text: "el olor de un fracaso" },
    { id: 246, text: "una obra de teatro escrita por un perro" },
    { id: 247, text: "el tesoro que nadie quiso encontrar" },
    { id: 248, text: "un reloj que se detuvo en el peor momento" },
    { id: 249, text: "una biblioteca llena de excusas" },
    { id: 250, text: "un huracán de disculpas" },
    { id: 251, text: "el ruido de un corazón roto" },
    { id: 252, text: "una lámpara que siempre dice la verdad" },
    { id: 253, text: "el silencio incómodo de un ascensor" },
    { id: 254, text: "un ejército de gansos enojados" },
    { id: 255, text: "un museo de errores" },
    { id: 256, text: "una taza de té llena de secretos" },
    { id: 257, text: "el fantasma de un bolígrafo perdido" },
    { id: 258, text: "una disculpa escrita en una servilleta" },
    { id: 259, text: "un dragón que colecciona sueños rotos" },
    { id: 260, text: "el peor meme de internet" },
    { id: 261, text: "el hombre que vendió la luna" },
    { id: 262, text: "una silla que nunca deja de chirriar" },
    { id: 263, text: "la biblioteca de los libros más odiados" },
    { id: 264, text: "el olor de un secreto revelado" },
    { id: 265, text: "un tigre con miedo a las ovejas" },
    { id: 266, text: "el sonido de la lluvia en una tumba" },
    { id: 267, text: "una brújula que solo apunta al sur" },
    { id: 268, text: "un sombrero lleno de abejas" },
    { id: 269, text: "el zapato de un gigante olvidado" },
    { id: 270, text: "una torre de cartas que nunca cae" },
    { id: 271, text: "el tesoro más decepcionante del mundo" },
    { id: 272, text: "una nevera que canta ópera" },
    { id: 273, text: "el día que olvidé mi propia sombra" },
    { id: 274, text: "una paloma con complejo de artista" },
    { id: 275, text: "el sonido de una promesa rota" },
    { id: 276, text: "un león que se convirtió en vegetariano" },
    { id: 277, text: "una máquina del tiempo que solo va al martes" },
    { id: 278, text: "un espejo que nunca dice la verdad" },
    { id: 279, text: "el elefante que se olvidó de todo" },
    { id: 280, text: "una vela que nunca se apaga" },
    { id: 281, text: "un fantasma que canta boleros" },
    { id: 282, text: "un viaje que nunca terminó" },
    { id: 283, text: "una mesa llena de culpas" },
    { id: 284, text: "el perfume de la nostalgia" },
    { id: 285, text: "un recuerdo que no me pertenece" },
    { id: 286, text: "una nube con forma de arrepentimiento" },
    { id: 287, text: "un rompecabezas con piezas que sobran" },
    { id: 288, text: "una carta que nunca llegó a destino" },
    { id: 289, text: "el llanto de un payaso solitario" },
    { id: 290, text: "un camello que extraña el desierto" },
    { id: 291, text: "la última lágrima de un héroe olvidado" },
    { id: 292, text: "una canción que nunca termina" },
    { id: 293, text: "el peor chiste contado en una boda" },
    { id: 294, text: "el sonido de la verdad" },
    { id: 295, text: "una piedra que siempre rueda" },
    { id: 296, text: "un circo sin público" },
    { id: 297, text: "la peor selfie del mundo" },
    { id: 298, text: "una botella de vino llena de lágrimas" },
    { id: 299, text: "un juego que nunca se puede ganar" },
    { id: 300, text: "el mejor error de mi vida" },
    { id: 301, text: "cantar el himno nacional mientras lloras" },
    { id: 302, text: "romper en llanto durante una entrevista de trabajo" },
    { id: 303, text: "darle un abrazo a un maniquí pensando que es tu amigo" },
    { id: 304, text: "que te despidan por reírte en el funeral de tu jefe" },
    { id: 305, text: "escribir una carta de renuncia en Comic Sans" },
    { id: 306, text: "confundir a un sacerdote con un mago" },
    { id: 307, text: "revisar tu historial de búsquedas con tus padres mirando" },
    { id: 308, text: "preguntarle a un bebé si cree en el libre albedrío" },
    { id: 309, text: "recibir una herencia que incluye únicamente deudas" },
    { id: 310, text: "discutir con un loro y perder" },
    { id: 311, text: "descubrir que el test de ADN dice que no eres humano" },
    { id: 312, text: "olvidar cómo respirar justo antes de un beso" },
    { id: 313, text: "perder un concurso de talentos contra un gato" },
    { id: 314, text: "despertarte en medio de una cirugía" },
    { id: 315, text: "ser arrestado por bailar en una biblioteca" },
    { id: 316, text: "llamar por error a tu jefe 'papá'" },
    { id: 317, text: "que te pidan que expliques qué haces con tu vida" },
    { id: 318, text: "enamorarte de la voz de una inteligencia artificial" },
    { id: 319, text: "que el test de Rorschach revele que amas los finales tristes" },
    { id: 320, text: "descubrir que tu terapeuta también necesita terapia" },
    { id: 321, text: "aplaudir en el momento equivocado en un velorio" },
    { id: 322, text: "decirle 'te amo' a alguien que solo te pidió la hora" },
    { id: 323, text: "celebrar tu cumpleaños y darte cuenta de que nadie fue invitado" },
    { id: 324, text: "olvidar la letra del 'Feliz Cumpleaños' mientras cantas" },
    { id: 325, text: "soñar que vuelves a la escuela... y quedarte atrapado allí" },
    { id: 326, text: "aparecer en las noticias como 'la persona más torpe del mundo'" },
    { id: 327, text: "revisar el espejo y darte cuenta de que no tienes reflejo" },
    { id: 328, text: "darte cuenta de que llevas 20 minutos hablando solo" },
    { id: 329, text: "ser bloqueado en redes sociales por tu propio perro" },
    { id: 330, text: "confesar algo terrible... y que nadie te esté escuchando" },
    { id: 331, text: "perder una discusión con tu versión más joven de ti mismo" },
    { id: 332, text: "descubrir que la Ouija solo quería preguntarte por el Wi-Fi" },
    { id: 333, text: "ser la razón por la que cancelaron la fiesta de fin de año" },
    { id: 334, text: "reírte de un chiste... y darte cuenta de que eres el chiste" },
    { id: 335, text: "decir 'te felicito' en un funeral" },
    { id: 336, text: "encontrarte con un exorcista que te dice: 'Me equivoqué de dirección'" },
    { id: 337, text: "ver a tu clon vivir mejor que tú" },
    { id: 338, text: "dar un discurso épico... al público equivocado" },
    { id: 339, text: "bailar en la oscuridad y darte cuenta de que no estás solo" },
    { id: 340, text: "tener un déjà vu en un déjà vu" },
    { id: 341, text: "descubrir que la persona que te gusta está comprometida... contigo" },
    { id: 342, text: "que te aplaudan por algo que no hiciste" },
    { id: 343, text: "decir 'hasta luego' en una llamada que ya colgó" },
    { id: 344, text: "despertarte en un funeral y darte cuenta de que es el tuyo" },
    { id: 345, text: "quedarte atrapado en un ascensor con tu peor enemigo" },
    { id: 346, text: "cantar karaoke en un idioma que no hablas" },
    { id: 347, text: "ver tu autobiografía escrita por alguien que te odia" },
    { id: 348, text: "darte cuenta de que todo tu currículum es mentira" },
    { id: 349, text: "olvidar el nombre de tu pareja durante una presentación" },
    { id: 350, text: "ser abucheado por un grupo de abuelitas" },
    { id: 351, text: "intentar explicar el sentido de la vida en tres palabras" },
    { id: 352, text: "ser reemplazado en tu trabajo por un pez dorado" },
    { id: 353, text: "descubrir que tus amigos solo existen en tu imaginación" },
    { id: 354, text: "equivocarte de casa durante una sorpresa de cumpleaños" },
    { id: 355, text: "tener una revelación importante... en el baño" },
    { id: 356, text: "intentar huir de un lugar, pero olvidar cómo correr" },
    { id: 357, text: "hacer una llamada accidental a tu ex en vivo" },
    { id: 358, text: "descubrir que el horóscopo tenía razón" },
    { id: 359, text: "gritar 'bingo' en medio de una misa" },
    { id: 360, text: "reírte tan fuerte que te despiertas a ti mismo" },
    { id: 361, text: "pedir un deseo, pero que el genio te odie" },
    { id: 362, text: "ser inmortal... pero aburrirte de inmediato" },
    { id: 363, text: "darte cuenta de que eres el único humano en el cuarto" },
    { id: 364, text: "perder una apuesta que nunca hiciste" },
    { id: 365, text: "intentar dar un abrazo grupal y quedar fuera del grupo" },
    { id: 366, text: "hacer una broma tan mala que alguien se desmaya" },
    { id: 367, text: "bailar solo en una pista llena de personas" },
    { id: 368, text: "darte cuenta de que llevas los zapatos al revés todo el día" },
    { id: 369, text: "dar un consejo de vida que tú mismo no sigues" },
    { id: 370, text: "ser olvidado en una reunión familiar" },
    { id: 371, text: "gritar en la ducha porque olvidaste que no estabas solo" },
    { id: 372, text: "ser el único que no entiende el chiste" },
    { id: 373, text: "darte cuenta de que te equivocaste de película en el cine" },
    { id: 374, text: "escribir un poema hermoso... y que todos se rían de él" },
    { id: 375, text: "tener una crisis existencial durante una clase de yoga" },
    { id: 376, text: "confundir un semáforo con una señal de Wi-Fi" },
    { id: 377, text: "darte cuenta de que nunca aprendiste a nadar" },
    { id: 378, text: "saludar a alguien... que no te está mirando" },
    { id: 379, text: "darte cuenta de que no sabes sumar durante un examen" },
    { id: 380, text: "reírte solo para darte cuenta de que no fue gracioso" },
    { id: 381, text: "pedirle a un fantasma que se calme" },
    { id: 382, text: "confundir un pingüino con un ladrón" },
    { id: 383, text: "explicar algo complejo y darte cuenta de que nadie entiende" },
    { id: 384, text: "tratar de huir de tu sombra" },
    { id: 385, text: "ser parte de una protesta que no entiendes" },
    { id: 386, text: "hacer una presentación... con diapositivas vacías" },
    { id: 387, text: "darte cuenta de que olvidaste usar pantalones" },
    { id: 388, text: "intentar hacer reír a alguien... y que empiece a llorar" },
    { id: 389, text: "confundir a tu abuela con una celebridad" },
    { id: 390, text: "cantar una canción equivocada en un karaoke" },
    { id: 391, text: "darte cuenta de que estás en la boda equivocada" },
    { id: 392, text: "reconocer a alguien, pero no saber de dónde" },
    { id: 393, text: "despertarte hablando un idioma que no conoces" },
    { id: 394, text: "revelar un secreto por accidente en un grupo de WhatsApp" },
    { id: 395, text: "pedir disculpas a alguien que no se dio cuenta de tu error" },
    { id: 396, text: "decir 'feliz año nuevo'... en mayo" },
    { id: 397, text: "darte cuenta de que nadie escuchó tu gran discurso" },
    { id: 398, text: "correr hacia una puerta que se abre hacia dentro" },
    { id: 399, text: "darte cuenta de que todos están en silencio excepto tú" },
    { id: 400, text: "gritar '¡Lo logré!' justo antes de fallar" }
    // ... agrega muchas más para tener variedad
  ];
  