// whiteCards.js
module.exports = [
    { id: 1, text: "un mapache con un cuchillo" },
    { id: 2, text: "una tostadora en llamas" },
    { id: 3, text: "mi vecino construyendo un cohete casero" },
    { id: 4, text: "un desfile de elefantes en mi jardín" },
    { id: 5, text: "mi perro hablando francés" },
    { id: 6, text: "una invasión de patos agresivos" },
    { id: 7, text: "una piñata llena de abejas" },
    { id: 8, text: "la cara de mi jefe en un billete" },
    { id: 9, text: "una bicicleta que no avanza" },
    { id: 10, text: "un pingüino fumando un cigarro" },
    { id: 11, text: "un robot con crisis existencial" },
    { id: 12, text: "una tormenta de fideos" },
    { id: 13, text: "una vaca con zapatos de tacón" },
    { id: 14, text: "el silencio incómodo en una boda" },
    { id: 15, text: "un cactus llorando lágrimas reales" },
    { id: 16, text: "mi peor calificación convertida en tatuaje" },
    { id: 17, text: "el olor de la desesperación" },
    { id: 18, text: "mi profesor disfrazado de payaso" },
    { id: 19, text: "una serpiente con sombrero" },
    { id: 20, text: "la abuela del presidente" },
    { id: 21, text: "una nevera llena de helado derretido" },
    { id: 22, text: "un unicornio robando bancos" },
    { id: 23, text: "una silla de ruedas con turbo" },
    { id: 24, text: "un tanque lleno de peces parlantes" },
    { id: 25, text: "una momia haciendo yoga" },
    { id: 26, text: "el espíritu vengativo de mi microondas" },
    { id: 27, text: "mi mejor amigo siendo arrestado por robar queso" },
    { id: 28, text: "un oso intentando hacer panqueques" },
    { id: 29, text: "un genio que solo concede deseos inútiles" },
    { id: 30, text: "la planta que se comió a mi hermana" },
    { id: 31, text: "el apocalipsis zombi, pero lento" },
    { id: 32, text: "un dragón con miedo a volar" },
    { id: 33, text: "una almohada llena de secretos" },
    { id: 34, text: "el álbum de fotos de un extraterrestre" },
    { id: 35, text: "una carta de amor mal escrita" },
    { id: 36, text: "un barco pirata con solo un pirata" },
    { id: 37, text: "una camisa que te odia" },
    { id: 38, text: "un huracán de chanclas" },
    { id: 39, text: "la peor sopa de la historia" },
    { id: 40, text: "un enjambre de mosquitos en un teatro" },
    { id: 41, text: "un payaso enojado" },
    { id: 42, text: "el espíritu de mi ex" },
    { id: 43, text: "una sandía explosiva" },
    { id: 44, text: "mi abuela bailando reguetón" },
    { id: 45, text: "un político buscando sinceridad" },
    { id: 46, text: "una conferencia sobre cómo fracasar" },
    { id: 47, text: "un panadero que odia el pan" },
    { id: 48, text: "el jefe que nadie invitó al cumpleaños" },
    { id: 49, text: "la peor canción del mundo en un loop infinito" },
    { id: 50, text: "una familia discutiendo en la fila del supermercado" },
    { id: 51, text: "un cuadro abstracto que da miedo" },
    { id: 52, text: "la leyenda del baño cerrado en un tren" },
    { id: 53, text: "un gato con más seguidores que yo en redes sociales" },
    { id: 54, text: "una pila de tareas que nunca desaparecerá" },
    { id: 55, text: "el cumpleaños de alguien que olvidaste" },
    { id: 56, text: "un pez peleando con su reflejo" },
    { id: 57, text: "mi esperanza perdida en una caja de pizza vacía" },
    { id: 58, text: "una fiesta que nadie recuerda" },
    { id: 59, text: "una estatua de cera que parece viva" },
    { id: 60, text: "la palabra 'perdón' mal utilizada" },
    { id: 61, text: "la selfie de un criminal en fuga" },
    { id: 62, text: "una rifa con premios inútiles" },
    { id: 63, text: "una pelea absurda por un cargador de móvil" },
    { id: 64, text: "el reloj que siempre marca la hora incorrecta" },
    { id: 65, text: "una lista de deseos que incluye 'desear menos'" },
    { id: 66, text: "un payaso en una rueda de prensa" },
    { id: 67, text: "la lámpara que juraste que era mágica" },
    { id: 68, text: "un tren que no llega a ningún lado" },
    { id: 69, text: "un traje que huele a arrepentimiento" },
    { id: 70, text: "el libro que me arruinó la infancia" },
    { id: 71, text: "un perfume llamado 'desesperación'" },
    { id: 72, text: "la casa que todos dicen que está embrujada" },
    { id: 73, text: "un globo que arruinó un funeral" },
    { id: 74, text: "la nota de suicidio de un robot" },
    { id: 75, text: "una cabra en una sala de espera" },
    { id: 76, text: "el beso de Judas" },
    { id: 77, text: "un cirujano con miedo a la sangre" },
    { id: 78, text: "un paquete que nunca debí abrir" },
    { id: 79, text: "la última palabra de un pirata" },
    { id: 80, text: "un dictador en un concurso de canto" },
    { id: 81, text: "un pastel que explota al cortarlo" },
    { id: 82, text: "un regalo de navidad lleno de lágrimas" },
    { id: 83, text: "la razón por la que me dejaron en el altar" },
    { id: 84, text: "el payaso de las pesadillas de mi infancia" },
    { id: 85, text: "un perro al que nunca le lanzaron la pelota" },
    { id: 86, text: "un incendio en una fábrica de peluches" },
    { id: 87, text: "una pluma que escribe insultos sola" },
    { id: 88, text: "un tiburón en una piscina pública" },
    { id: 89, text: "el arte moderno más ofensivo que he visto" },
    { id: 90, text: "el premio Nobel de la mediocridad" },
    { id: 91, text: "una silla eléctrica con Wi-Fi" },
    { id: 92, text: "el ruido de un sueño roto" },
    { id: 93, text: "el bebé más feo del mundo" },
    { id: 94, text: "una iglesia vacía en navidad" },
    { id: 95, text: "el apocalipsis más decepcionante de la historia" },
    { id: 96, text: "un espíritu vengativo en mi microondas" },
    { id: 97, text: "la única persona que me dijo la verdad" },
    { id: 98, text: "un cupcake con mensajes pasivo-agresivos" },
    { id: 99, text: "el fantasma de mi mala decisión" },
    { id: 100, text: "un paraguas roto en medio de una tormenta" },
    // ... agrega muchas más para tener variedad
  ];
  